name: Update Fundamentals

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fundamentals update
        run: python update_fundamentals.py
        env:
          DB_URL: ${{ secrets.DB_URL }}
