name: Update Fuel

on:
  schedule:
    - cron: "2 17 * * *"
    - cron: "2 8 * * *"
  workflow_dispatch:

jobs:
  update-fuel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python update_fuel.py
